### ISSUE TITLE
Getting error when trying to run with Expo and react native

### ISSUE THREAD

**Issue by minifisk** [antoniocosentino/react-native-quiz-input#1]
I'm getting the following error, any idea what is causing it?

`Invariant Violation: Tried to register two views with the same name RNGestureHandlerButton
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:4 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
at node_modules/metro-runtime/src/polyfills/require.js:203:6 in guardedLoadModule
at http://192.168.0.114:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:196673:3 in global code

Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:4 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError`

**Comment by antoniocosentino** [comment]
Hello @minifisk, sorry for the late reply. I'm currently unable to replicate this issue. Can you provide me with some more info about the setup?

In particular I'd like to know:
- If you are already using `react-native-gesture-handler` in your project. In that case, which version?
- What Expo SDK version are you using?

It would be great if you could setup a snack on Expo.dev where the error is reproducible. This would be of great help for understanding the issue better.

Thanks.

**Comment by antoniocosentino** [comment]
closed due to non reproducibility

**Comment by denizutku** [comment]
Having the same issue with `"expo": "~48.0.6"` and no other `react-native-gesture-handler` dependency in the project
